apiVersion: v1
kind: Secret
metadata:
  name: trainbook-secrets
type: Opaque
data:
  DB_URL: bW9uZ29kYitzcnY6Ly9yZXNlcnZhdGlvbkFkbWluOk1BTkFHRVJAZ29kZnJleS1kYi1jbHVzdGVyLmNpdHdmNW4ubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUdvZGZyZXktREItQ2x1c3Rlcg==
  DB_NAME: cmVzZXJ2YXRpb24=  # 'reservation' encoded in base64
